site_name: Llm Resources
site_url: https://ossirytk.github.io/llm_resources
repo_url: https://github.com/ossirytk/llm_resources
nav:
      - Home: index.md
      - For Beginners: beginners.md
      - Information: information.md
      - AI Tube: ai_tube.md
      - AI Reddit: ai_reddit.md
      - Models: models.md
      - Prompts: prompts.md
      - Tools: tools.md
      - Tools(Dev): tools_dev.md
      - Datasets: datasets.md
theme: readthedocs
